version: '3'
services:
  todofront:
    image: todofrontend
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - todoback
    environment:
      - REACT_APP_API_HOST=todoback
  todoback:
    image: todobackend
    ports:
      - 3001:3001
    restart: always
  tests:
    image: todotests
    environment:
      - FRONT_HOST=todofront
    depends_on:
      - todoback
      - todofront
